name: Build SimpleRecorder

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore FluentScreenRecorder.sln

    - name: Build with GitHub script
      shell: cmd
      run: |
        echo Running GitHub build script...
        call github-build.bat
        
    - name: Fallback build if main build fails
      if: failure()
      shell: cmd
      run: |
        echo Main build failed, trying fallback build...
        call fallback-build.bat

    - name: Upload any build outputs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: SimpleRecorder-BuildOutput
        path: |
          FluentScreenRecorder/AppPackages/
          FluentScreenRecorder/bin/
          **/*.appx
          **/*.msix
          **/*.exe
        if-no-files-found: warn

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          FluentScreenRecorder/AppPackages/**/*.msix
          FluentScreenRecorder/AppPackages/**/*.appx
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}